### ISSUE TITLE
Lib submission flow

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#105]
# TODO
- [x] /assignments endpoint
- [x] /submit-libs endpoint
- [x] submission of all empty libs on the front end should have no effect (defaults will get used)
- [x] Add a "sorry, your ringleader didn't tell you to click the button yet" flow for when a participant fetches libs before the ringleader closes the seder (this is part of calling the /get-libs endpoint)
  - [x] Handle the failure to grab libs (there will be no assignments) on the /play page. Put a Try Again button. Only front-end changes are needed. The back end already sends 500 if the participant item for a participant has no assignments column.
- [ ] Make sure none of the non-cookie-checking midware uses res.locals.gameName or res.locals.roomCode (go to req or query instead so people can't lie) _Covered in another issue_
