### ISSUE TITLE
Add front-end tests for completed pages

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#110]
Especially Pick Your Script and Your Room Code. Refactor while doing this.

## TODO
- [x] Explain page
  - [x] Add tests (most importantly, the link)
  - [x] Increase padding on /explain
- [x] Move some boilerplate to `setup.js`, based on Enzyme's [jest guide](https://airbnb.io/enzyme/docs/guides/jest.html) and [installation guide](https://airbnb.io/enzyme/docs/installation/). *This provides an error like "you an only override certain Jest options" from `create-react-app`, so this is on hold. Actually, it worked. I was tipped off by [this](https://github.com/airbnb/enzyme/issues/1265).*
- [x] /pick-script
- [x] MenuAppBar
- [ ] Find out how to not ship test-supporting files like `lib/getFourScripts.js`.
- [ ] Get rid of un-needed components and files and related tests.
- [ ] Deal with the tests taking ~15s.
- [ ] Factor out dependencies with network interaction
  - [ ] Pick Your Script's call to /scripts should be contained in a function that is passed down to it through props from App.
