### ISSUE TITLE
Script reading flow

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#113]
# TODO
- [x] /read-roster endpoint
- [x] /read-roster page
  - [x] some not done
  - [x] everyone done
- [x] In cookie-check, fail if room code or game name is in both query and body
- [x] /script endpoint
- [x] UI: pull from /script into state at /read
- [x] Mock out the script so I can work on /read
- [x] Make a Page component
- [x] Increment the PageIndex from Page
- [x] Fix indent presentation
- [x] Put something after "no, we'll use someone else's device."
- [x] Show "ready to read, hand to the reader" screen before displaying page 1 and later
- [ ] Page back navigation button
- [x] Show the prompt when reading
- [ ] Set up veryawesomepassover URL (make a separate Issue for this)
