### ISSUE TITLE
Ringleader Game Name submission flow

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#120]
# TODO
- [x] Add input box and related method(s)
- [x] Handle failed join
- [x] Display the Roster Page on successful join
- [ ] Set App.state.isRingleader. *I'll do this when it's needed for something*
