### ISSUE TITLE
Put the 2018 script into the scripts repo

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#134]
# TODO
- [ ] Deal with the missing h2/3s from the Hebrew words
- [ ] Make sure indentation is present when needed
- [ ] Support stage directions
