### ISSUE TITLE
User sign-in

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#173]
# TODO
- [x] Save the user in storage
- [ ] MLJSAPI error `ENOENT: no such file or directory, uv_cwd`
  - [ ] Update the version of SAM CLI that I'm patching
  - [ ] Try with the unpatched version
  - [ ] Apply the patch and try again
  - [ ] Set up a dev stage for a branch
- [ ] Make the current user state survive a refresh
- [x] Remove the user in storage on logout
- [ ] Make the app bar show the user
- [ ] Add a logout link to the app bar (don't worry about logging in after the home page for now)
- [ ] Front end
  - [x] Save the user info to storage and take it out of the location. _Not possible with user info in query/search without refreshing the page. Options: (1) have a new front-end page like "logging you in as name/email that goes away once the logged-in info is saved to storage, (2) put the user info in the hash when you come back from MLJSAPI (but this might interfere with hash-routing), or (3) just refresh the home page (but what if someone tries an interaction before the refresh starts?). I'll start with (1)._
  - [ ] Send access token ~and refresh token~ (don't send the refresh token to the front end--save it in the db (?)) cookies. The id tokens are too short-lived to use for back-end access. The three tokens should only be sent as cookies if all three, received together, are valid (right?). In any case, a user's browser-side tokens should never be from different issuances from AWS's TOKENS endpoint.
  - [ ] Make sure I can exchange refresh tokens for access tokens.
  - [x] Make sure we're save from [JWT vulnerabilities](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/), and don't hard-code the alg during verification (use what the header says). We are--we just have to use a patched version of a certain library.
