### ISSUE TITLE
Google Docs add-on for script editing

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#178]
# TODO
- [x] Display the highlighted text in the sidebar.
- [x] Have inputs for the prompt, example, sentence, and default for the selected word(s).
- [x] ~Have the Create Lib button switch to Confirm Lib (disabled) after Create is clicked.~ Add an Insert Lib button that inserts the lib formatted for Mad Liberation.
  - [x] Insert example.
  - [x] Insert sentence.
  - [x] Insert default.
- [x] Handle the nothing-selected case (insert libbed text). _It already inserts text._
  - [x] Get it to highlight the text. Start by inserting a created text element in the handler.
- [x] Handle the whole-element-selected case.
- [x] Handle the partial-element-selected case.
- [x] Don't add a space (or at least don't make the space yellow) when the cursor (no selection) is not adjacent to a space.
- [x] Bug: Create Lib breaks after the first create.
- [x] Highlight libs in yellow after they are libbed by the sidebar. There will be no other record of libs.
- [ ] ~Add a cancel button to the Create flow.~
- [x] Auto-populate the prompt with the highlighted text on Create click.
- [ ] ~Provide a dialog saying text must be highlighted to create a lib if Create is clicked with nothing highlighted. Can I respond to text highlighting?~ Actually, insert at the cursor if no text is highlighted. I will have to handle the case where the cursor or selection is within an existing lib.
- [x] Transform and export into a format consumable by Mad Liberation.
  - [x] Get the current user's name (so that we can create a folder like _Mad Liberation Scripts - douglasnaphas_.
  - [ ] ~Create the _MadLiberation-username_ folder.~ _I'll just export a doc so that I don't have to worry about idempotency with respect to existing folders_
  - [x] Set up testing for the transformation function.
  - [x] Prepend titles and h1s with `#`, h2s with `##`, etc.
  - [x] Handle page breaks. Make sure the output for upload/transform begins with a page marker.
- [ ] If Create Lib is clicked when the selection is inside an existing lib (detected by `{{` `}}`), on Create click, expand the selection to grab the whole lib, and auto-populate the populated fields, before proceeding with the Create flow.
- [ ] Handle stage directions inside `[[` `]]`. Add Create/Insert Stage direction button(s) and flow.
- [ ] Add a validate button and flow.
- [ ] Limit textarea width dynamically (to container width?).
- [ ] Improve the feel of button presses (you can barely tell when one is depressed).
- [ ] XSS?
- [ ] Can I distribute as an add-on within a new Very Awesome Arts Google organization?
- [ ] Add the ability to condense lib presentation in the doc to just the prompts, for readability.
- [ ] Prohibit libbing anywhere but in a text body (or support libbing in, for example, a header).
- [ ] Make it not support minimally structurally correct data (don't insert without a prompt and a default).
- [ ] Enable drafting a lib in the boxes while nothing is highlighted. Clicking _Create Lib_ probably should not blow out the text in the boxes. Maybe _Prompt_ should not exist as a box. The prompt could be whatever is highlighted.
- [ ] Handle the multiple full elements selected case.
- [ ] Handle the cross-element case where one or two of the elements is partially selected.
- [ ] Improve the look and feel, especially the button-click.
- [ ] Figure out how to do logging that is accessible after the script runs.

# Acceptance criteria
- [ ] The add-on should be publicly available through Docs (this might not be necessary, since a general audience can't get any use out of it until other features are added to passover.lol).
- [ ] You should be able to highlight a word and associate attributes (prompt, example, sentence, default) to it.
