### ISSUE TITLE
Update dependencies 2019-09

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#191]
# TODO
- [ ] Update int tests to make sure the "submit all these" button is not showing on /play until the last screen. I could maybe do this on master and then rebase on my feature branch, to ensure that the bug is not released. _Probably not necessary, as I can update unit tests on this behavior when I add unit tests to /play_
- [x] Fix the new bug (screenshots below) of the "submit all these" button always being present.
  - [x] See if the /read flow shows a "previous page" button on the first page. `grep -rIn --color -C3 hidden src/` showed that in `Page.js` I hide a button by setting `hidden` on its containing `div`. */read works as intended--setting hidden on the containing div works*
  - [ ] Try to reproduce and find documentation explaining the unexpected `hidden` behavior. _Not worrying about documentation for now_
  - [x] Implement a solution. This includes setting up a POC illustrating the current approach failing to hide, and the selected approach successfully hiding. Options:
    1. Set `hidden` on the `div`, not the `Button`.
    1. Conditionally render. Maybe set up an Issue to adopt this throughout the project if this is chosen.
    1. Use [visibility](https://developer.mozilla.org/en/docs/Web/CSS/visibility).
