### ISSUE TITLE
Allow re-join for leaders after room code generation

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#223]
# TODO

- [x] Save the tuple (id token nickname, id token email, Cognito username, JWT subject claim) in the db with /get-cookies. Use subject as the partition key and Cognito username as the sort key, possibly with a random value salting the sort key (it can't salt the partition key because I need the partition key exactly for lookups). This is so that when I do db lookups it is better for them not to be by client-supplied nickname and/or email, because these will have come from JS and are less trusted.
- [x] Save an index value when saving the userinfo: ~~> 0 for a userinfo item.~~ Key directly on the user_email.
- [x] Figure out whether the same email address when used through different id providers (Google and Facebook) results in the same sub claim. _This results in different subs. I confirmed with AWS support. You have to call a link accounts API to link them. I'm just going to automatically link them, indirectly, by assuming that users with the same email are the same person._
- [x] Make a middleware that flags whether or not this request is attempting to be an authenticated request. _It does this by saving something in res.locals.user if req.query.user is populated._
- [x] Make a middleware that pulls the access_token and refresh_token from cookies if this is an authed request
- [x] Have `flagAuthedRequests` look to post params
- [x] Add tests to `checkJwt`
- [x] Have `getCognitoClientSecret` take another argument, `local`, to build in conditionality.
- [x] Add the conditional `getCognitoClientSecret` to the `authenticate` series.
- [ ] Hydrate the user from local storage. **If there is a user in local storage, that means the user is logged in as far as the client is concerned. This is OK because all "log out" does is clear the user from local storage.**
- [ ] Implement `refreshAccessToken`.
- [ ] Revise `checkJwt` to use the refresh token if it's checking an access token and it's expired
- [ ] Revise `checkJwt` to be conditional (that is, have the middleware it returns be conditional)
- [ ] `checkJwtConditionally`
- [ ] ~Make a middleware that saves the logged-in user's info to `res.locals`.~ Make middleware that validates the JWT in `res.locals.access_token`.
  - [ ] Factor the logic in `getMadLnJwksFromAws` to a non-middleware function, so that I can call it conditionally. I could do [this](https://stackoverflow.com/a/21293587/2260686) instead.
- [ ] Make /room-code in MLJSAPI note the logged-in user, if one is present, in the db. Do this by comparing the `user-nickname` and `user-email` received in params to the info received in the access token (but how will I know who the access token is for?).
- [ ] Make an API /seders endpoint that lists the user's seders.
- [ ] /room-code should return whether or not the transaction was successfully associated with the user supplied in the query param, and the front-end should respond by logging out whatever user it thought was logged in, or by prompting them to log in again.
- [ ] New page (with inbound link): /my-seders.
- [ ] Double-check that I don't have any async functions/middlewares that throw directly (they should try-catch instead as explained [here](https://expressjs.com/en/guide/error-handling.html)).
