### ISSUE TITLE
Update the roster automatically when someone joins the user's current Seder

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#250]
Use WebSockets.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Does the connect handler have access to cookies?

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Make it so that POSTing to the WS URL makes the POST contents show up in the roster.
- [ ] Eliminate duplicates in the roster. _No, check again_ should not cause the name to show up twice.
- [ ] Make a new user appearing in the seder in Dynamo POST to the WS URL.

**Comment by douglasnaphas** [comment]
[Streaming from Dynamo to WS](https://spin.atomicobject.com/2021/01/06/websockets-aws-dynamodb-updates/)

**Comment by douglasnaphas** [comment]
[Using promise() to send Dynamo requests](https://www.fernandomc.com/posts/eight-examples-of-fetching-data-from-dynamodb-with-node/)

**Comment by douglasnaphas** [comment]
I need to [use an escape hatch](https://github.com/aws/aws-cdk/issues/17874#issuecomment-991272057) to use [event filtering](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html) on my DynamoDB stream.

**Comment by douglasnaphas** [comment]
I used [this example](https://github.com/aws/aws-sdk-js/issues/1963#issuecomment-508210959) for mocking the AWS SDK in my WebSocket handlers.

From that comment:

```js
const AWS = require('aws-sdk');

const mockS3GetObject = jest.fn();
jest.mock('aws-sdk', () => {
    return {
        S3: jest.fn(() => ({
            getObject: mockS3GetObject
        }))
    };
});

describe('...', () => {
    beforeEach(() => {
        mockS3GetObject.mockReset();
    });

    test("...", async () => {
        mockS3GetObject.mockImplementation((params) => {
            return {
                promise() {
                    return Promise.resolve({ Body: "test document" })
                }
            };
        });
        expect(await functionUnderTest()).toEqual("test document");
    });
});

// E.g., in another module
const AWS = require('aws-sdk');
async function functionUnderTest() {
    const resp = await new AWS.S3(...).getObject(...).promise();
    return resp.Body;
}
```
