### ISSUE TITLE
Make sure my signout is a real signout

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#253]
I think I currently have a halfhearted signout, that leaves the cookies in place.

**Comment by douglasnaphas** [comment]
This definitely belongs in v4.

**Comment by douglasnaphas** [comment]
I should set an expiration time on the cookies, in case people don't actively logout.

**Comment by douglasnaphas** [comment]
I should make sure there's an expiration date on my non-JWT cookies as well.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Add a /clear-cookies endpoint.

**Comment by douglasnaphas** [comment]
On deleting cookies server-side:
https://stackoverflow.com/questions/5285940/correct-way-to-delete-cookies-server-side#:~:text=Using%20an%20Expires%20attribute%20in,expiration%20date%20in%20the%20past.

**Comment by douglasnaphas** [comment]
I'm re-prioritizing this ahead of WebSockets. I think I only temporarily put WebSockets ahead of it because I was curious whether the WebSocket connect handler receives cookies. It does.

**Comment by douglasnaphas** [comment]
I'm still continuing work for this on the 250-ws1 branch for now, though.

**Comment by douglasnaphas** [comment]
What about users who still have old cookies in their browsers for Passover 2022?

**Comment by douglasnaphas** [comment]
Do I even need access and refresh tokens? I'm not delegating authorization like with OAuth2.0. Should I be issuing my own cookie? If I do, what happens when it expires? How about...it's expired, and the person has to log in again. I bet my frontend doesn't handle that course of events (expired cookies of any kind) at all.

**Comment by douglasnaphas** [comment]
I think a big part of the whole problem around signout, gh-331, etc, is that my frontend is confused about who is signed in. It should, as part of this or any of this batch of Issues:

1. Ask the backend on each load for an authoritative decision about whether the cookie sent with the request is for a logged-in user, and if so, the logged-in user's email address.
2. If they're not a logged-in user, but they once were (?), like if the cookie is found but expired (but if I'm expiring cookies by a cookie attribute, an expired cookie will never get sent, so I won't be able on the backend to distinguish between a user who logged in too long ago and a user who has never logged in), or if some state on the front end claims that the user is logged in, then they should go to a you-have-been-logged-out page.

**Comment by douglasnaphas** [comment]
Ugh, what if someone logs in, joins a seder, logs out in another tab, and submits their libs in the tab where they're logged in?

**Comment by douglasnaphas** [comment]
I should stop sending the id token to the client, and instead associate the identity server-side with the…sub? Id token on the client creates multiple sources of truth.

**Comment by douglasnaphas** [comment]
The whole login/logout behavior is getting really hard to manage. I think I need to list all the different features I want, how I want it to work.

**Comment by douglasnaphas** [comment]
I think I do want to move to a passover.lol-generated opaque cookie. Advantages:

- Less noise in the dev tools.
- Less data sent around.
- Less backend complexity because I can throw out the refresh token logic. I can just have the opaque cookie last as long as I want it to, that is, as long as the refresh token would have been valid for. When the opaque cookie expires, they're logged out, just as they would have been whenever their refresh token expired.
- Less backend complexity around cookie-checking after initial login.
- No more abuse of access tokens--I should not be using OAuth2 access and refresh tokens because I'm not doing delegation of authorization.

I should still, during the cookie-checking process, check back with Cognito to see if the person has deleted their user.

**Comment by douglasnaphas** [comment]
Side note: maybe the backend auth'd user recordkeeping should be limited to "this email address was this user in these rooms."

**Comment by douglasnaphas** [comment]
# APIGW StepFunctions integration
[Example](https://github.com/aws/aws-cdk/issues/1465#issuecomment-811591998)
```typescript
    const generatorStartIntegration = new CfnIntegration(
      this,
      'GeneratorStartIntegration',
      {
        apiId: httpApi.httpApiId,
        integrationType: HttpIntegrationType.LAMBDA_PROXY,
        integrationSubtype: 'StepFunctions-StartExecution',
        connectionType: HttpConnectionType.INTERNET,
        credentialsArn: apiRole.roleArn,
        description:
          'integrate with the generator implmented by step functions',
        payloadFormatVersion: PayloadFormatVersion.VERSION_1_0.version,
        requestParameters: {
          StateMachineArn: transactionGenerator.stateMachineArn,
          Input: '$request.body.input',
        },
        timeoutInMillis: 1000 * 10,
      },
    );
```

**Comment by douglasnaphas** [comment]
# To-do
- [ ] Confirm fetches that should require login cookies still work after logout
- [ ] Update itest to have the logged-in browser start a seder, go back home, join a seder, log out, do the fetch to confirm it's logged out, then log in, see its seders, and re-join the seder it joined (not started) before resuming the existing itest
- [ ] Get the fetch-after-logout test passing
- [ ] Start issuing opaque cookies
- [ ] Start checking opaque cookies
- [ ] Stop issuing JWTs
- [ ] Stop checking JWTs

**Comment by douglasnaphas** [comment]
I want to free the frontend from worrying about the sub. It's annoying. It's leaky. The frontend's authenticated requests to the backend should just specify the email address.

**Comment by douglasnaphas** [comment]
I should probably record, check, and update cookie expiration time on the backend.

**Comment by douglasnaphas** [comment]
# Very important
Gracefully handle 400s or similar returned from the backend due to a login cookie that expired mid-Seder.

**Comment by douglasnaphas** [comment]
The login cookie should be non-session.

**Comment by douglasnaphas** [comment]
I'm quite worried about how the front-end will handle expired logins.

**Comment by douglasnaphas** [comment]
# TODO 2022-03-15
- [ ] Have the frontend reasonably handle expired sign-ins. I might have adequate instructions already, since I think with some 400s I say "if you are logged in, try logging out," "try in a different browser," etc.

**Comment by douglasnaphas** [comment]
I might need to bring back some kind of /id endpoint. If you load a new page after signing in, and you have a valid cookie in your browser, you could be kind of signed in without your UI telling you that you are. This could probably be addressed after web sockets, because you aren't really signed in when this happens. The front end has to affirmatively include the email address in requests, even if there is a valid cookie, for anything to happen on behalf of the user.

**Comment by douglasnaphas** [comment]
I might need to bring back some kind of /id endpoint. If you load a new page after signing in, and you have a valid cookie in your browser, you could be kind of signed in without your UI telling you that you are. This could probably be addressed after web sockets, because you aren't really signed in when this happens. The front end has to affirmatively include the email address in requests, even if there is a valid cookie, for anything to happen on behalf of the user.

**Comment by douglasnaphas** [comment]
gh-400 is created to handle invalidating the opaque cookie server-side.
