### ISSUE TITLE
Deploy mljsapi, madliberationjs to a CloudFront distro with API Gateway and S3

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#254]
# TODO
- [x] Run the API locally with SAM, from `madliberation/`. _We're actually going to run with straight node, because incorporating SAM into the Docker setup is too hard, because SAM itself starts up a container_
- [x] Set up nginx config to reverse proxy from a port to another service
- [ ] ~Access the API (running with SAM outside of Docker) via port that talks to nginx. This will involve running `sam local start-api` with the `--docker-network` option.~ _Won't do. There's no way for the nginx conf file to reference the out-of-Docker running API, at least not without doing container networking that I don't know how to do. Running with node is close enough to how it will be run in prod_
- [ ] ~Run the API locally with SAM, Docker, and docker-compose.~
- [ ] ~Try to run the SAM CLI Docker container from docker-compose. Try something like mapping the volume from `madliberation/mljsapi`.~
- [x] Add an S3 bucket.
- [ ] (live site) Add a div to the frontend on the About page containing the config values that I will inject, if they are present.
- [ ] (live site) Inject the values (api.passover.lol for the backend, and the redirect URI) that I need for the app to function normally, and confirm they are present in the attributes of the added div
- [ ] Switch the frontend to using the injected values, with the current location as default. Validate by observing the (failing) call on the new frontend to /scripts.
