### ISSUE TITLE
Get login (no social provider) working in turnkey

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#274]
# TODO
- [x] Update Puppeteer.
- [x] Add a Cognito User Pool.
- [x] Create a bucket in the stack to hold the Cognito user pool client secret (the _client secret bucket_).
- [x] Add the user pool id to stack output.
- [x] Get the user pool id in save-client-secret.sh
- [x] Get the client secret in save-client-secret.sh
- [ ] Try using Dynamo with DAX instead, because I'm not sure how to get the S3 content, as opposed to the file, with the S3 SDK, although I do this for the scripts in `mljsapi`... _Deferring, going to try with S3_
- [x] Save the client secret to the client secret bucket after deploying the stack.
- [x] Have the backend take in the client secret bucket name as an env var.
- [x] Update itest to have a player click log in.
- [x] Find out how to programmatically get the hosted UI URL. Maybe output it? Try with the AWS CLI. It will need to get fed to the fronted, and to itest.
- [x] Do some assertions about the location, specifically asserting that it's what's expected given the Cognito login URL.
- [x] See the above test fail in CI.
- [ ] ~~Add a prettier config to package.json at the madliberation level. Read through the options and figure out which I want.~~ _Issue #277 created for this._
- [ ] Get the test working, so that clicking the login button takes you to the right URL.
  - [x] Hard-code the URL.
  - [x] Watch it pass in dev.
  - [x] Merge and watch it fail in higher envs. Does failing in test end the build, or does it still attempt prod? it should not attempt prod if test fails, good time to check this. _The build did not proceed after the test env integration test step failed, as desired._
  - [ ] ~~Save/retrieve the Cognito domain with SSM param store.~~ _Deferring, not sure if this would work given the build steps._
  - [ ] ~~Make frontend/ require an env var for the build to happen, via checking in a build script.~~ _This might need to be reconsidered, since I'm not sure if `REACT_APP_` vars are read at build or run time. Update: [they're read at build time](https://create-react-app.dev/docs/adding-custom-environment-variables/), so they go into the bundle. Still not sure if this is the right approach, as opposed to receiving a redirect from a backend endpoint._
  - [x] Make `backend` `app.test.js` testing that `app` returns 301 from /login, using Jest.
  - [x] Make the backend /login test look for different outcomes based on the important env vars.
  - [x] Feed the Cognito-related env vars to backend in the CDK webapp stack.
  - [x] Get the login test passing with a redirect returned from /prod/login, which will be linked from the login button.
    - [x] Dev
    - [x] Test
    - [x] Prod
- [x] Pull the IDP URL from Configs, isolating `process.env` accesses there.
- [ ] Use API calls to create and confirm a user for testing, in the build. Better yet, with the SDK in the itest script.
- [ ] Use test user in itest.
- [ ] Remove the user after the itests.
- [ ] Only check for nickname from the JWTs in getUserInfo.
- [ ] Get /get-cookies working.
