### ISSUE TITLE
Add social login to turnkey

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#285]
# TODO
- [ ] See if I can store an encrypted SSM param and then retrieve it. _Not doing this. I'm going to use GitHub Actions Secrets to store secrets, because it's easier and disguises them if they accidentally wind up in Action output._
- [x] Set up an Action step called like "Secrets roll call" that says "Facebook app secret present" if the Facebook app secret is present in Actions Secrets, or "Facebook app secret absent" otherwise. Likewise for Google and Amazon.
- [x] Add the index(es) that support(s) `/seders` and `/sedersJoined`.
- [ ] Facebook. Note: for all providers, try committing directly on master, because this is domain-name dependent, in that I will tell the providers which domain names are allowed, like passover.lol, and I only have prod set up as deploying to a custom domain.
  - [ ] Add the necessary info that Mad Liberation needs for Facebook as params in bin/.
  - [ ] Modify the Facebook app configs to allow mad-liberation.com.
- [ ] For each app, especially Facebook, are there restrictions in place as a result of having my app in an unconfirmed or development state?
