### ISSUE TITLE
Set up reasonable steps and automation for running itest locally

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#377]
# TODO
- [x] Add `npm itest`. It should allow for the `--slow` option, and tell you when you haven't supplied the right env vars.
- [x] Make CI use `npm itest`.
- [ ] Are `AWS_DEFAULT_REGION` and `AWS_REGION` both necessary? I think they are, because I think one is for the SDK. They are both set in CI. _Resolving this is not a priority right now._
- [x] Add a smoke test option to the itest app. [Do this](https://github.com/douglasnaphas/madliberation/issues/311#issuecomment-801508837) as part of it. This will take the place of https://github.com/douglasnaphas/madliberation/issues/311.
- [x] Am I always printing `pick-your-script-page.jpeg` from the itest app? _Addressed by 09056af3c4e5a9eac72b920852c2eb0385d2e284. Fix will be deployed whenever this Issue's branch is merged._

**Comment by douglasnaphas** [comment]
I think it's time for `npm itest`, and for _Interaction with the project should be through `npm run ...`, that is, `package.json` should present the inerface for the project, and CI and local dev should interact with the project using that interface_ to be elevated to a Turnkey principle, or some other recommended guiding principle of development.

**Comment by douglasnaphas** [comment]
How about automating checks on the Turnkey principles, like AWS Well-Architected?

**Comment by douglasnaphas** [comment]
https://stackoverflow.com/questions/17319100/iterating-over-variable-name-in-bash-script

for v in REQVARNAME OTHER REQVARNAME ; do if [[ ! -n “${!v}” ]] ; then echo “need bar named ${!v}” ; exit 1 ; fi ; done

**Comment by douglasnaphas** [comment]
Done.
