### ISSUE TITLE
Reduce bundle and Lambda sizes

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#389]
# TODO
- [ ] Make sure everything possible (typescript?) is moved from dependencies to devDependencies in package.json files. Does that even impact the artifact sizes?
- [ ] Try to get rid of packages
- [ ] Tree-shaking, other best practices
