### ISSUE TITLE
Add automated tests for running locally

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#445]
Just test what I have so far, so I know I'm not breaking it. Try to do async, in a way that doesn't unduly delay the build, and/or to do a bunch of things in parallel in my Actions.

**Comment by douglasnaphas** [comment]
https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

**Comment by douglasnaphas** [comment]
https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs

**Comment by douglasnaphas** [comment]
# TODO
For this and gh-440 combined.
- [ ] On `master`, lay out the job structure I want (build, test-front, test-back, test-content, test-overall, deploy-test, itest-test, deploy-prod, itest-prod, deploy-prod2, itest-prod2, itest-devenv). `build` means install and build the top-level repo and sub-repos, because I don't want to deal with recombining artifacts. Use placeholders for most, don't even deploy from the new jobs yet.
- [ ] Push to master, rebase 440 off it.
- [ ] Set up master's job structure on the 440 branch, and build it out for the feature branch build.
- [ ] Merge 440 to master.
- [ ] Build out all the jobs, except itest-devenv, on master.
- [ ] Rebase 443 off master.
- [ ] Build out the devenv test job on the 443 branch.
- [ ] Port all feature branch test jobs to master and vice versa, on 443.
- [ ] Merge 443 to master.

**Comment by douglasnaphas** [comment]
# Job structure
```
build -> test-overall -> deploy-test -> itest test -> deploy prod
      -> test-front
      -> test-back
      -> test-content
                                -> deploy prod2
```

**Comment by douglasnaphas** [comment]
Deploy and itest for each env could be grouped together.

**Comment by douglasnaphas** [comment]
De-prioritizing behind actually building new pages to support the 2023 (plan-ahead) flow. Things like running locally can be added as part of completing plan-ahead features, which will often require fresh new SPAs.

**Comment by douglasnaphas** [comment]
I'm super giving up on running locally, it's awful and wasted months.
