### ISSUE TITLE
Add a minimal Plan Seder page

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#451]
# TODO
- [x] Merge in my work on gh-443 and friends, so I'm not wondering which branch to come back to (maybe?).
- [ ] ~~Make a new landing page with Next and Tailwind.~~ _I'm staying with MUI, not using Tailwind. I don't need to create my own design system._
- [ ] ~~Serve the app from all paths when retrieving from S3. See what happens when I load abcd.cloudfront.net/some-path.~~
- [ ] ~~Make a new App page in frontend/pages/.~~
- [ ] ~~Make a new About page in frontend/pages/.~~
- [ ] ~~Link frontend/pages/App to frontend/pages/About.~~ _This and the last few items are stricken out. I'm going to try it using the [Agreement Principle](https://github.com/douglasnaphas/madliberation/issues/451#issuecomment-1373782468), which may very well be regarded as bad web design since it renounces dynamic paths. Anyway I'm not going full Next.js._
- [ ] ~~One CDK app per frontend, separate from backends. Same bin. So they can deploy in parallel.~~ _Actually, not. They can't be in separate CDK apps, for now, because CloudFront needs to know about each frontend and each backend._
- [x] Make my build only act on the frontend if it's changed. ~~Likewise content.~~
  - [x] Option 1: tags (preferred option, since the GitHub Actions option described below in Option 2 requires restructuring of my workflows, i.e. breaking the frontend builds into their own workflows and dealing with reassembling them so that itest runs after everything)
    - [x] Take a look at the frontend bucket in AWS.
    - [x] Get a bucket-tagging script working from the CLI locally ([guide](https://stackoverflow.com/questions/68002405/how-to-add-tags-to-an-s3-bucket-without-deleting-the-existing-tags-using-aws-cli) for appending a tag)
    - [x] Tag buckets with a Git commit (in metadata?) whenever I deploy to buckets.
    - [x] Only build frontend if it differs from the commit the bucket is tagged with.  Don’t just not deploy it, don’t build it.
    - [ ] Repeat for content, maybe. _Deferred. Max content/ build-deploy time is like 10 seconds._
  - [ ] ~~Option 2: use something like [on: push.<path>](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to only run a workflow when a path changes~~ _Exactly what I want isn't supported_
- [ ] ~~#472~~ _Not worth it for now. Tons of effort_
- [ ] ~~Add an info/ SPA. Build and deploy only on change.~~ _Deferring. Not essential._
- [x] Add a ~~plan/~~ create-haggadah/ SPA.
- [x] If there is no SHA tag on a frontend* bucket, deploy to it. This is to avoid not deploying on the first run for a new frontend, which is what happened [here](https://github.com/douglasnaphas/madliberation/actions/runs/3995590206/jobs/6854755763).
- [x] Set up /create-haggadah to run locally.
- [ ] ~~Move files for running locally to dev/~~ _Abandoning local dev for now, because it won't stop trying and failing to hot reload_
- [x] Get dev deploy working
- [x] Make accordions not be one-at-a-time only
- [x] Make the accordions based on the steps
- [x] Put step bodies into accordions
- [ ] ~~Make the stepper steps (1) expand the corresponding accordion, (2) navigate you to the accordion~~ _I've abandoned the stepper_
- [ ] ~~See if I can pass along info like ?return-page=/create-haggadah with [IDP URI](https://github.com/douglasnaphas/madliberation/blob/e0358f6191acbf0684633a4dbc0caae420d3191e/infra/lib/madliberation-webapp.ts#L268)~~ _Forget IDPs, etc, I'm just emailing people their info_
- [ ] ~~Login step: on load, mark the step done if a GET to /id or equivalent succeeds~~
- [ ] ~~Login step: link in new tab to get you to log in.~~
- [ ] ~~Make the stepper stay at the top.~~ _The stepper is abandoned, no need for multiple core UI elements~~
- [x] Why isn't my deploy-only-if-changed logic working in my frontends?
- [ ] ~~Taint the sha tag in dev-deploy.sh~~ _Deferring, not even really remembering what this means_
- [ ] ~~Make v2/scripts read directly from the content bucket.~~ _Maybe some day, but not soon. I need to deactivate scripts, etc, and I don't want to revisit the Google Apps Script right now to generate the JSON elements that would contain meta-info._
- [x] Lock the pick-script and your-email sections of /create-haggadah/index.html once the link has been generated.
- [ ] Add an "are you sure?" step to the _That's everyone_ flow
- [ ] Map /create-haggadah/ and /create-haggadah to /create-haggadah/index.html.
- [x] Bring the main and feature-branch workflows in sync.

**Comment by douglasnaphas** [comment]
I'm reimagining this. I think it would be better to start using Next.js instead of Create React App on the main existing frontend, and to tackle the whole UX redesign by (1) having the URL say what seder you're in, and (2) making the journey look more like the one at the MUI showcase app [d-cide.me](https://d-cide.me).

**Comment by douglasnaphas** [comment]
The Issue description was formerly _Add a minimal Plan Seder page_.

**Comment by douglasnaphas** [comment]
Do I want to abandon hash routing?

**Comment by douglasnaphas** [comment]
![Image](https://user-images.githubusercontent.com/5433410/209561706-0a8e9a5c-bece-4cd5-a035-2252367d61ab.png)

**Comment by douglasnaphas** [comment]
What if I cut /seders/<seder code> out of the path entirely, replacing just that string with /, rather than setting the whole uri to / if /seders/<seder code> occurs?

I would really like to be able to handle paths like passover.lol/seders/abcdef.

**Comment by douglasnaphas** [comment]
Whatever I'm doing now seems to be able to handle /seders/seder-abcdef.

![Screenshot 2022-12-29 at 10 07 46 PM](https://user-images.githubusercontent.com/5433410/210030468-e469b9ec-c009-474c-9508-0029b7f2ca24.png)

**Comment by douglasnaphas** [comment]
Maybe I could put something in the frontend like: if /seders/seder-abcdef is in the path, the seder is abcdef. Forget React state.

I'd love to scope the seder cookie to a specific seder, but that would require path rewriting for backend, and maybe even path re-architecting.

**Comment by douglasnaphas** [comment]
Trying to see what kind of POST happens for this comment. I'm wondering if there's a POST to /issues/451/comment, since I might want to POST to something like /seders/seder-abcdef/assignments.

**Comment by douglasnaphas** [comment]
I'm pretty set on modifying my backend to speak in terms of /prod/seders/seder-abcdef/roster, and my frontend to have the hash routes all look like anchors within whatever page they belong in, instead of separate pages.

**Comment by douglasnaphas** [comment]
I think it's time to kick off async/non-blocking Actions steps. The immediate need is that I want to run through a Seder from https://passover.lol/seders/seder-abcdef, but I also need to test that the local dev env works. As I write this, it occurs to me that tests of https://passover.lol/seders/seder-abcdef should block.

**Comment by douglasnaphas** [comment]
What if every truly static page were...a static page? That is, how about an About page as separate independent assets at https://passover.lol/about?

**Comment by douglasnaphas** [comment]
# Crisis

I am in crisis. I really need to figure out what the meaning of the different parts of my URL should mean.

## Problems
Structuring the app as single-page is causing a lot of problems. [This post](https://javascript.plainenglish.io/how-single-page-applications-broke-the-web-design-bd18d4ddcdab) describes some of them:

> For example, the concept of URLs makes sense for document based websites, but needs to be re-thought from the SPA perspective. The URLs are often artificially injected by using the browser’s History API; this seems like some kind of a hybrid state instead of a long term solution. If not carefully taken care of, some SPAs break simple features like forward and back buttons in the browser, resulting in a user experience which is far from ideal. Even the simplest things, like the title element of SPA, needs special handling either with JavaScript or server-side-rendering approaches.

In the context of passover.lol, the problem is well illustrated by the experience of a user, Rachael, who submitted her libs, then hit the Back button on her browser, and basically died as a result.

## Strategies

## Tradeoffs 
### Accept some re-loading
Accept that you'll be loading a new page sometimes. For example, if someone is at passover.lol, and they want to get the static info like the privacy policy or the contact form, loading a new page from passover.lol/privacy-policy or passover.lol/contact is acceptable. Someone looking for that info is not in a rush.

### Accept longer build times

### Accept diminished code re-use

**Comment by douglasnaphas** [comment]
I should probably make sure, somehow, that a frontend’s build doesn’t happen if everything’s the same, or my build will take too long, even for me.

**Comment by douglasnaphas** [comment]
# For conditionally getting tags
```
[cloudshell-user@ip-10-2-42-252 ~]$ aws s3api get-bucket-tagging --bucket douglasnaphasmadliberation-frontendbucketefe2e19c-n1dqq5595b7i
{
    "TagSet": [
        {
            "Key": "aws:cloudformation:stack-name",
            "Value": "DouglasnaphasMadliberation451-next-webapp"
        },
        {
            "Key": "aws:cloudformation:logical-id",
            "Value": "FrontendBucketEFE2E19C"
        },
        {
            "Key": "aws:cloudformation:stack-id",
            "Value": "arn:aws:cloudformation:us-east-1:287213416300:stack/DouglasnaphasMadliberation451-next-webapp/a0c9adc0-6c62-11ed-88cd-0e723a38b8a9"
        },
        {
            "Key": "aws-cdk:auto-delete-objects",
            "Value": "true"
        }
    ]
}
[cloudshell-user@ip-10-2-42-252 ~]$ aws s3api get-bucket-tagging --bucket bucket-in-doug-lab2-account

An error occurred (NoSuchTagSet) when calling the GetBucketTagging operation: The TagSet does not exist
[cloudshell-user@ip-10-2-42-252 ~]$ echo $?
254
[cloudshell-user@ip-10-2-42-252 ~]$ if aws s3api get-bucket-tagging --bucket bucket-in-doug-lab2-account ; then echo "tags" ; else echo "no tags" ; fi

An error occurred (NoSuchTagSet) when calling the GetBucketTagging operation: The TagSet does not exist
no tags
[cloudshell-user@ip-10-2-42-252 ~]$ echo $?
0
```

**Comment by douglasnaphas** [comment]
It should be "Create Haggadah," not "Plan Seder."

**Comment by douglasnaphas** [comment]
I think I'll merge this once you can use /create-haggadah, which I may link to with text like _Plan Seder_, to see the populated scripts.

**Comment by douglasnaphas** [comment]
Local running should take the form of a build of static assets, with a self-written Node server proxied and serving the static pages.

**Comment by douglasnaphas** [comment]
I just learned session storage is tab-specific, and local storage is not. I think I'll be using session storage for refresh survival for all flows for v2023. It will be much better to not have to reason about multiple tabs.

**Comment by douglasnaphas** [comment]
I do think /plan-seder is a better name than /create-haggadah. (1) The non-leader participants will also be involved in creating the haggadah, but not in planning the seder. (2) /plan-seder better captures the idea of coming back to the page for your specific hasn't-happened-yet seder.

**Comment by douglasnaphas** [comment]
The don't-do-anything-if-no-change-to-frontend logic seems to have falsely detected no changes to frontend from #459: https://github.com/douglasnaphas/madliberation/actions/runs/4120488399/jobs/7115327754.

**Comment by douglasnaphas** [comment]
The preview could be at /read?sp=<some identifier of the **s**cript being **p**reviewed (hence **sp**)>. Later on populated scripts could be at /read?s=<identifier of the seder>&pw=<shared secret that makes it possible to conceal the seder>.

Implement some kind of rate limiting like: reject after something like 100 requests in the same minute for the same seder. Do calculations to ensure that the rate limit allows all reasonable use, but prevents brute force. Though that could turn into a DoS, if someone keeps brute forcing...

**Comment by douglasnaphas** [comment]
Promising code example for sending email: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/ses-examples-sending-email.html.

**Comment by douglasnaphas** [comment]
This might be some progress (/edit-link sending something back).

![Screenshot 2023-03-11 at 9 12 52 AM](https://user-images.githubusercontent.com/5433410/224489476-0cd8e805-1123-484d-97e8-c4156ab01f98.png)

**Comment by douglasnaphas** [comment]
That's interesting. Apparent seder code collision on 25th try. Expected it no sooner than 27th.

![Screenshot 2023-03-11 at 9 43 51 AM](https://user-images.githubusercontent.com/5433410/224490952-30d4a328-983e-4438-920c-94e45f8f6be1.png)

**Comment by douglasnaphas** [comment]
Oh boy. Failure followed by success. Might not be handling collisions correctly. Time to do [this](https://github.com/douglasnaphas/madliberation/issues/491#issuecomment-1464925670) so I can better test collision logic in CI. I now don't trust it. Maybe a collision has just never happened.

![Screenshot 2023-03-11 at 9 45 08 AM](https://user-images.githubusercontent.com/5433410/224491008-01771af4-7b08-4e8b-bad3-d5debe9577a7.png)

**Comment by douglasnaphas** [comment]
Actually, the collision logic probably works, it just exceeded the max retries, maybe.

![Screenshot 2023-03-11 at 9 49 17 AM](https://user-images.githubusercontent.com/5433410/224491198-fdf6fbb3-60b5-479f-9d8b-94a58ca97a73.png)

**Comment by douglasnaphas** [comment]
Yeah, I think we're good enough. Not going to parameterize room code length quite yet. Probably not for 2023.

![Screenshot 2023-03-11 at 9 51 31 AM](https://user-images.githubusercontent.com/5433410/224491296-61206a05-cc2b-4e69-85ce-1501fc50700b.png)

**Comment by douglasnaphas** [comment]
Tested collision logic manually successfully with 5e756f5e637e5db13132018e5e6ed86ff1b79aed.

**Comment by douglasnaphas** [comment]
I think I can stop logging the email address value.

![Screenshot 2023-03-11 at 10 31 50 AM](https://user-images.githubusercontent.com/5433410/224493236-5773004c-2506-4f20-828e-fda8f2cac93c.png)

**Comment by douglasnaphas** [comment]
Looks like I've got `data.data.sederCode`, not `data.sederCode`.

![Screenshot 2023-03-11 at 7 13 31 PM](https://user-images.githubusercontent.com/5433410/224517244-95dff31f-9794-478d-922a-8499179bfe48.png)

**Comment by douglasnaphas** [comment]
If I'm going to lock the form choices (script and Your Email) after the link is obtained, and I want to provide them a permalink, maybe the form should just land them at /create-haggadah/edit.html?sederCode=<the seder code>&pw=<the pw>, like a normal form lol.

**Comment by douglasnaphas** [comment]
Verified manually that removing participants works.

**Comment by douglasnaphas** [comment]
Verified manually that the leader is joined from /create-haggadah/index.html's Submit button.

**Comment by douglasnaphas** [comment]
Dollar signs in dialog, doesn't list the leader. Maybe do a new page after all.

![Screenshot 2023-03-20 at 2 46 52 PM](https://user-images.githubusercontent.com/5433410/226437319-3f376680-5023-4947-baa5-194bc5f6508d.png)
![Screenshot 2023-03-20 at 2 47 11 PM](https://user-images.githubusercontent.com/5433410/226437321-29196483-2484-4937-9aa2-0d87fc44f6b3.png)

**Comment by douglasnaphas** [comment]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.UpdatingListElements

**Comment by douglasnaphas** [comment]
I'm going to have putParticipantLink happen at seder-join time for each participant. I don't want close-seder waiting for assignments then waiting for the participantPw to be written individually in each participant item.

**Comment by douglasnaphas** [comment]
Nice.

![Screenshot 2023-03-22 at 12 38 37 PM](https://user-images.githubusercontent.com/5433410/226975473-89b68285-7b10-432e-9f94-2cc6fc664496.png)

**Comment by douglasnaphas** [comment]
The plan-seder flow works, merging and closing. Time to start working on the blanks flow, then the read flow.

![Screenshot 2023-03-22 at 9 21 38 PM](https://user-images.githubusercontent.com/5433410/227074524-5d1e0f27-b4e3-4e7d-a2da-d3a56a4ad13f.png)
