### ISSUE TITLE
Read from pre-submitted libs

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#497]
Complements gh-418.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Set up a blank-ish read page that tries to fetch the script
- [ ] Save a read_pw on sederCode creation
- [ ] Create validateReadPw.js
- [ ] Make /script send the script
- [ ] Make read.tsx display the script

**Comment by douglasnaphas** [comment]
Looks like `answers_map` keys are strings.

![Screenshot 2023-03-28 at 8 21 29 AM](https://user-images.githubusercontent.com/5433410/228234375-471b2c7f-37a8-4d73-a8e2-a539a9bdcdf4.png)

**Comment by douglasnaphas** [comment]
Degraded performance for GitHub Actions

https://www.githubstatus.com/incidents/chnz8v3m9dqm

**Comment by douglasnaphas** [comment]
That looks like a successful script get...

![Screenshot 2023-03-28 at 1 55 32 PM](https://user-images.githubusercontent.com/5433410/228326564-a3635f24-cfef-4ac0-b1c2-69d5dbd5473c.png)

**Comment by douglasnaphas** [comment]
What if the only way you could set the page number for /read was by setting the hash, and navigating among different pages were accomplished by setting the hash? Does an `<a>` to a different hash on the current page refresh the page? Does a NextJS `Link`?

**Comment by douglasnaphas** [comment]
Maybe https://www.30secondsofcode.org/react/s/use-hash/

**Comment by douglasnaphas** [comment]
I'm off by one. That's the second page, and I can't click _Previous_.

![Screenshot 2023-03-29 at 3 03 12 PM](https://user-images.githubusercontent.com/5433410/228641729-8e7766fc-3c23-4841-806d-d7390c2ac369.png)
