### ISSUE TITLE
Automatically advance to the next prompt

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#521]
Or at least add a Next button. This is a commonly requested feature.

![Screenshot 2023-04-03 at 9 57 35 AM](https://user-images.githubusercontent.com/5433410/229531675-5dae14d6-9d31-4c59-b63c-957e74c9bb6a.png)

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Update itest to expect updated button text
- [ ] Fix button text
- [ ] Update itest to expect auto-advancement
- [ ] Implement auto-advancement
- [ ] Expect a Previous button
- [ ] Add a Previous button
- [ ] Expect the Previous button to display the previous lib
- [ ] Make the previous button display the previous lib
- [ ] No Previous button on the first lib
- [ ] No Next button on the last lib

**Comment by douglasnaphas** [comment]
A non-linear stepper has a lot of the behaviors I'm building: https://mui.com/material-ui/react-stepper/#non-linear.
