### ISSUE TITLE
Add a 2023 script

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#524]
# TODO
- [ ] Clarify that each page should be read by a new person. Maybe. Might want to defer to next year, and communicate this in person to the remaining known Seder leader for 2023.
- [ ] Update README in AppsScript/ to not say that it's a submodule
- [ ] Test 2023, 2022, and 2019 Magid in parallel
- [ ] Proofread
