### ISSUE TITLE
Tests for page flow from Home Page

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#90]
# Acceptance criteria
- [x] Test that clicking on links works as intended, probably from `App.test.js`.
- [x] Test that the expected links are present in each component.

# TODO
- [x] Modify the int. test to make one successful assertion using puppeteer
- [x] Make the build do one failing assertion with puppeteer
- [x] Make the build deploy to a staging bucket
- [x] Make the API allow calls from the staging bucket.
- [x] Test the staging bucket
- [x] Put the integration test after the staging bucket deployment and before the prod bucket deployment
