### ISSUE TITLE
Create the Your Room Code Page

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#91]
# TODO
- [x] Create an API endpoint: (haggadah_id) -> unique_room_code.
  - [x] Make the endpoint create a seder with a fixed Room Code
  - [x] Make the endpoint re-create the seder with the same fixed Room Code, updating a timestamp attribute each time
  - [x] Make the endpoint not re-create a seder when the Room Code already exists
  - [x] Make an injectable dependency on a candidateFactory method (a generator?) that produces a series of candidate Room Codes
  - [x] Put placeholder scripts in the scripts bucket
  - [x] Put the script paths in the haggadahs DB
  - [x] Make it take the haggadah or script as a parameter (go with the bucket URL, ARN, or bucket/object as "path") and save it in the seders DB
  - [x] Observe script paths going into the seders table
  - [x] Display the Room Code on the client
