### ISSUE TITLE
Create the Enter Room Code flow

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#98]
# TODO
- [x] Add a nickname field.
- [x] Make the Join button only enabled when the code matches the regex, and the nickname is supplied.
- [x] Make lowercase letters ok to enter in the Room Code box
- [x] Make /room-code include an empty list of participants in the attributes for the created seder.
- [x] Make /join-seder append to the list of participants.
- [x] Make a /join-seder endpoint: post(roomCode, gameName) -> (success if roomCode exists and gameName is not taken, failure otherwise) *Disregarding/deferring unchecked sub-tasks*
  - [x] Make /join-seder take the roomCode and gameName in the post body
  - [x] Make /join-seder fail if the gameName is taken
  - [x] Make /join-seder fail if roomCode is invalid. Check some "valid" attribute on the seder, or check its age. Either set the valid attribute or rename/rethink the timestamp attribute in /room-code
  - [x] Make /join-seder generate a session key
  - [x] Make /join-seder send the session key back as a cookie
  - [x] Set expiration, http-only, and any other required attributes on the cookie
  - [x] See if a Game Name like 'zy=abc; ' breaks the cookie *It does*
  - [x] Do  /join-seder middleware with an array of callbacks, instead of separate app calls
  - [x] Add post-rejecting middleware for '/*' that 400s if the post body contains non-whitelisted characters in the fields
  - [x] Save the plain text participant name in the DB
  - [x] Make sure all interaction with DB attributes uses schema.js, including on the front end
  - [x] Query testing
    - [x] Add some lib_id: participant# entries for a seder, using the dashboard
    - [x] Query for the participants in a seder
    - [x] Have the query add a lib_id: participant# entry instead of adding the participant to a set on the seder
    - [x] Query for the lib_id: scripts# entries
  - [x] Break setting the cookie into separate middleware
  - [x] Make the Game Name cookie name a cookie-name-safe value (use a hash of the Game Name)
  - [x] Check what happens with Game Names with special characters
  - [x] Build blacklisting into server-side game name handling, since apparently = and ; really mess up cookies
  - [ ] 400 from empty-string Game Names
  - [x] Blacklist ';', '=', '/' in Game Name (don't whitelist, because it might break internationalization), front end. Don't put them in the box if they're typed.
  - [ ] Prepend something to the session cookie name so it doesn't conflict with other cookies
  - [x] Make /join-seder save the session key in the DB
  - [ ] Make middleware that checks the session key in the cookie against the DB. Associate it with the route /submit-lib: (roomCode, gameName, lib id, answer) -> success | failure.
  - [ ] Verify that the cookie is working by hitting /submit-lib with and without it
  - [ ] Verify the expiration on the cookie is working by hitting /submit-lib with an expired cookie
  - [ ] Verify that the cookie cannot be accessed through JS
  - [ ] See what happens when multiple unexpired cookies get sent
- [x] Make all send()s from the API return data: update tests, then implementation
- [x] Do the Room Code/Game Name submission UI flow: participant
  - [x] On failed join, show a red message saying the choices were bad, try again
  - [x] On successful join, remove the input boxes, show a message saying "Wait til your Ringleader tells you your libs are ready, then click this button," and a new "get libs" or "answer some questions" button
- [x] Make variable content in a box or a different color or something (like when the game name and room code appear in text)
- [ ] Game Name submission UI flow: Ringleader. *This can be in another Issue*
- [x] Have the submitted nickname display on the App Bar (once confirmed)
- [x] Handle duplicate nickname choices (call one "The Second", or "Junior", for example). It would also be OK to reject the duplicate with "that name is taken."
- [x] Make submitting attempt to update the DB. Don't check existence of the Room Code or the nickname until submission. Don't worry about background pre-checking for now.
- [x] Make sure I have an Issue for an XSS review
